[project]
authors = ["me0ww <mewww733@gmail.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "pandas-tutorial.pixi"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
start = "jupyter lab"

[dependencies]
jupyterlab = ">=4.2.4,<5"
pandas = ">=2.2.2,<3"
pip = ">=24.2,<25"
